on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      RX_PROJECT_DIR: Rx.NET/Source/
      DOCFX_PROJECT_DIR: Rx.NET/Source/docfx_project
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet build --project ${{ env.RX_PROJECT_DIR }}/System.Reactive.sln

    - run: dotnet tool update -g docfx
    - run: docfx ${{ env.DOCFX_PROJECT_DIR }}/docfx.json

    - run: ls -la

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOCFX_PROJECT_DIR }}/_site
